### ISSUE TITLE
Error Copying Mainnet Blockchain.

### ISSUE THREAD

**Issue by Fillippone** [Stadicus/RaspiBolt#287]
Hello @Stadicus.
I progressed thru your guide until I get to the point where I have to copy the blockchain donwloaded on my computer to the Raspi.
I tried a copule of times and I got an error on the same exact 1045 block becasue a bad checksum. 

Errore di sistema.  Codice: 23.
Errore nei dati (controllo di ridondanza ciclico)

WinSCP stops and i cannot finish copying the rest  of the blocks (not sure i want to skip the error, btw).
Please note that the bitcoin core wallet I am running on my regular PC is fullly synced and apparently working well.
Do I have to redownload the whole blockchain?
 Can i download again that particular block? 
Is -reindex a relevant option here? (btw? how do exactely do a -reindex? only way i found is to add it on the shortcut link I use to start the Bitcoin Core program)
Thanks.
F.

**Comment by BobleChinois** [comment]
Hi, just in case, are you stopping the node when trying to copy the blocks? I got some issues before because I tried to copy blocks from a running node, not quite the same as what you got though.

**Comment by Fillippone** [comment]
Yes, of course i stop everything.

**Comment by BobleChinois** [comment]
That's strange, what I don't quite get if it is some kind of data corruption is how your node can still be up and running.

Did you have a look at issues on bitcoin repo? Like this one : https://github.com/bitcoin/bitcoin/issues/11627

**Comment by Fillippone** [comment]
yeah already checked. 
I am currently trying to reindex the database and also trying to redownload from scratch using a VM on a QNAP NAS.  Hopefully one of the two chain will be available to be copied. I was just wondering if there could have bee n a quicker way to fix it.

**Comment by BobleChinois** [comment]
Do you think it is a hardware issue?

**Comment by BobleChinois** [comment]
How did it turn out? Did you solve the problem?

**Comment by Fillippone** [comment]
Definetly not working. 
I am still running into problems.
I decided to try to setup a VM instance on Google Cloud, sync a bitcoin node there, and try to copy the blockchain on my PC from there. 
I used Remote Desktop to Drag and Drop the blockchain from the VM to my local PC, all went Smoothly. Then i used WinSCP to copy the blockchain from my PC to the RasPI: got the usual ERROR 23. 
Damn.
So I decided to detach the HDD from the RasPI, Mount on Windows using Paragon Parallel, then use the Mounted EXT4 HD as a local resource for the VM and copy there the blockchain (rirectly, without even touching my PC). All when smoothly. 
Detached the HDD from Windows, mounted on the RasPi, started bitcoind as per the guide.
When I start bitcoind It shut down with the following message: 



2018-12-29T07:28:32Z Opening LevelDB in /home/bitcoin/.bitcoin/chainstate
2018-12-29T07:28:32Z Fatal LevelDB error: IO error: /home/bitcoin/.bitcoin/chainstate/043229.ldb: Structure needs cleaning
2018-12-29T07:28:32Z You can use -debug=leveldb to get more complete diagnostic messages
2018-12-29T07:28:32Z Fatal LevelDB error: IO error: /home/bitcoin/.bitcoin/chainstate/043229.ldb: Structure needs cleaning
2018-12-29T07:28:32Z : Error opening block database.
Please restart with -reindex or -reindex-chainstate to recover.
2018-12-29T07:28:32Z Aborted block database rebuild. Exiting.
2018-12-29T07:28:32Z Shutdown: In progress...
2018-12-29T07:28:32Z scheduler thread interrupt
2018-12-29T07:28:32Z Shutdown: done


tried editing the bitcoin.conf with 

server=1
daemon=1
txindex=1
reindex

but nothing happens.
Tried starting bitcoind from command line with reindex, but failed miserably. 
I am stuck.

**Comment by BobleChinois** [comment]
Wow what a story, so it's finally working?

**Comment by Fillippone** [comment]
Node is still reindixing. 
Apparently copying the whole blockchain from VM is very risky. 
I am not in a rush and I am here to learn, but for sure it took longer than expected. 
Still haven’t figured out why it didn’t work with WINSpc anyway.

**Comment by Fillippone** [comment]
I think I have a decent setup. HDD is powered indipendently from Raspi.
I don’t know if you speak Italian, but here’s a pic of my assembly:

https://github.com/Fillippone/NodoBitcoinforDummies/blob/master/05.Assemblaggio_Hardware_del_nodo.md

I think I am plenty of Power.


Il giorno mer 9 gen 2019 alle 14:26 beinardus <notifications@github.com> ha
scritto:

**Comment by Stadicus** [comment]
Hej @Fillippone, do you still have this issue? Copying using SCP works very reliably in my experience, not sure how to help here.

**Comment by anonymoustrident** [comment]
I have just closed my thread on copying the main net over via SSH & SCP. SCP works better than SSH for my instance. I took quite an effort of time to transfer and delete . But please ensure that the connection is always up for the 6 hours and no interruption of network or computer going to sleep , network sleep etc.
