### ISSUE TITLE
Run LND and unlock wallet

### ISSUE THREAD

**Issue by Butterball6** [Stadicus/RaspiBolt#380]
Hello,

I made it to the LND wallet setup part of this guide and am having a issue when I unlock my wallet and try to check on the current state on LND

Message when trying to unlock wallet as admin user:
[lncli] rpc error: code = Unavailable desc = all SUbConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

Message when starting up lnd as bitcoin user, Says waiting for wallet password then: 
opened wallet
primary chain set to :bitcoin 
unable to connect to bitcoind: status code:401, response:""

I am new to this so I apologize if there was an easy fix in the troubleshooting. I tried to work through that, but wasn't having much success.

**Comment by Drewpower** [comment]
Hi...did you resolve this?

**Comment by Butterball6** [comment]
Hello! I have not yet resolved this any would appreciate any tips/pointers to get through it. I gave up for a while, but would love to get it working and will attempt it again.

**Comment by damianol** [comment]
I just ran into the same problem. I found some related discussion in a YouTube video (mainly from 14:56):

https://www.youtube.com/watch?v=Xg_0Zq85-6c

and on the lnd github:

https://github.com/lightningnetwork/lnd/issues/2614

but so far haven't been able to use them to find a solution.
