### ISSUE TITLE
Auto Unlock - Completes but does not unlock

### ISSUE THREAD

**Issue by ohenrik** [Stadicus/RaspiBolt#383]
I'm trying to figure out why my unlock script is not working. The script seems to run fine and appends the unlock message to the audit.log file. However the lightning node does not unlock. It just sits there waiting to be unlocked.

**Comment by Stadicus** [comment]
Any error message in the debug.log?

**Comment by ohenrik** [comment]
No messages in debug.log :(

**Comment by Stadicus** [comment]
Did you use the latest version of the unlock script?

**Comment by daniel-vera-g** [comment]
> I'm trying to figure out why my unlock script is not working. The script seems to run fine and appends the unlock message to the audit.log file. However the lightning node does not unlock. It just sits there waiting to be unlocked.

It would be nice you could share your problem on #352 
Then we have everything in one place and do not have to switch between issues

**Comment by Stadicus** [comment]
Yes, please check out the mentioned issue. Most issues arise from TLS problems.
