### ISSUE TITLE
DoS protection

### ISSUE THREAD

**Issue by deuteragenie** [Stadicus/RaspiBolt#390]
Maybe configuring iptables to protect against DoS would be good?

**Comment by Stadicus** [comment]
Do you have a specific configuration in mind? Feel free to submit a pull request.

**Comment by deuteragenie** [comment]
No time to look at this myself, but here is a good starting point:
https://javapipe.com/blog/iptables-ddos-protection/

**Comment by giulnz** [comment]
is not the purpose of "UFW" ? how do you know if you are ddosed ? which log to check ?

**Comment by Stadicus** [comment]
UFW is basiaclly a frontend to `iptables`, closing issue for now.
