### ISSUE TITLE
out of memory issue

### ISSUE THREAD

**Issue by lechatnieger** [Stadicus/RaspiBolt#394]
after updating to lnd beta 0.5.2, every two hours maybe, lnd, keeps locking the wallet, becauase of "out of memory issue", and start to print, only in ssh, not in the log file, hundreds, of lines 

Broadcasting batch of 7 new announcements
 runtime: out of memory: cannot allocate 2531328-byte block (1396277248 in use)
fatal error: out of memory
runtime stack:
runtime.throw(0x9dff80, 0xd)
 /usr/local/go/src/runtime/panic.go:608 +0x5c
runtime.largeAlloc(0x26a000, 0x2460100, 0xe524)
  /usr/local/go/src/runtime/malloc.go:1021 +0x120
runtime.mallocgc.func1()

than i manually unlock the wallet, and lnd starts again syncying and listening as usual.

What may cause, memory issue?

thank you in advance

**Comment by Stadicus** [comment]
I am not familiar with this issue. Could you post that directly to the LND github? If you are able to solve it or get some additional update, a quick update here is much appreciated.
