### ISSUE TITLE
TOR - CookieAuthFileGroupReadable warning

### ISSUE THREAD

**Issue by badokun** [Stadicus/RaspiBolt#406]
Just an observation on the TOR section. I've noticed this message in the logs
```bash
[warn] CookieAuthFileGroupReadable is set, but will have no effect: you must specify an explicit CookieAuthFile to have it group-readable.
```
 Should the configuration include this setting?

**Comment by daniel-vera-g** [comment]
You probably did not set the ownership the right way.
Check the [tutorial](https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_69_tor.md)

Check which users belong to the debian-tor group. If "bitcoin" is not there, which is most likely the case, you will need to add it and check again.

```
$ cat /etc/group | grep debian-tor
debian-tor:x:113:
$ sudo usermod -a -G debian-tor bitcoin
$ cat /etc/group | grep debian-tor
debian-tor:x:123:bitcoin
```

Modify the Tor configuration by uncommenting (removing the #) or adding the following lines.

```
$ sudo nano /etc/tor/torrc
# uncomment:
ControlPort 9051
CookieAuthentication 1

# add:
CookieAuthFileGroupReadable 1
```
