### ISSUE TITLE
Is there a way to change your LND wallet seed once setup is running?

### ISSUE THREAD

**Issue by walletofsatoshi** [Stadicus/RaspiBolt#438]
I want to change the LND 24 word seed without fresh install and keeping old setup. Is this possible?

**Comment by daniel-vera-g** [comment]
What do you define as `old setup`?

Quoting Roasbeef:

Remove `everything in the lnd application directory. The location depends on you OS, for example will be in ~/.lnd for linux.`

https://github.com/lightningnetwork/lnd/issues/1216
