### ISSUE TITLE
EPS v0.1.7 > 'Invalid Bitcoin address or script' Do not add the wallet master pub key to [watch-only-addresses]. 

### ISSUE THREAD

**Issue by xavierfiechter** [Stadicus/RaspiBolt#452]
> Add your wallet master public keys or watch-only addresses to the [master-public-keys] and [watch-only-addresses] sections. Master public keys for an Electrum wallet can be found in the Electrum client menu Wallet -> Information.

Do not add the wallet master pub key to [watch-only-addresses]. 

From the config.ini  

```
[watch-only-addresses]
#Add individual addresses to this section, for example paper wallets
#Dont use this section for adding entire wallets, instead use the
# above section `master-public-keys` 
```

**Comment by Septem151** [comment]
The wordage could be a bit better, but that's exactly what it's stating. It would be better I suppose to change this to:
> Add your wallet master public keys to the [master-public-keys] section and/or watch-only addresses to the [watch-only-addresses] section. Master public keys for an Electrum wallet can be found in the Electrum client menu Wallet -> Information.

or, to simply add "respectively" after the first sentence.
