### ISSUE TITLE
Error reading lock file /home/bitcoin/.lnd/.lnd.conf.swp: not enough data read

### ISSUE THREAD

**Issue by Kineticmb** [Stadicus/RaspiBolt#468]
I went to edit the lnd.conf but am receiving an error as above. At the top of the screen is says "New buffer". Where as previously it opened the lnd.conf file , it now opens a blank file with .swp tagged to the end of the file. 

Any idea how to resolve this and recover the file for editing? I assume its still there as the node is operating properly still. 

Many Thanks,

**Comment by Kineticmb** [comment]
Can anyone help me with this?

Thanks

**Comment by Stadicus** [comment]
Wow, super-old issue. Is your question still relevant? The problem you describe is usually due to multiple sessions working on the same file (or not closing it correctly).

**Comment by Kineticmb** [comment]
Hi Stadicus, 

No, all good thanks.
