### ISSUE TITLE
LND UPnP trouble

### ISSUE THREAD

**Issue by inssnach** [Stadicus/RaspiBolt#470]
Hey guys, 

I'm trying to setup my RaspiBotlt and it seems that I have a known issue by letting my pi connecting to the rest of the world. 
When starting the Raspberry Pi and the LND daemon the following error occurs. I can #nat=true in the config and everythings seems to be working. So my guess it is somewhere between the pi and the router. The fixed IP in the LAN is 192.168.178.72, so I changed everything according to that IP in the ufw, as shown below. 

-- Logs begin at Wed 2019-07-17 15:05:01 CEST. --

Jul 17 21:20:28 Crypthusiast lnd[3379]: 2019-07-17 21:20:28.334 [INF] SRVR: Scanning local network for a UPnP enabled device
Jul 17 21:20:29 Crypthusiast lnd[3379]: 2019-07-17 21:20:29.369 [INF] LNWL: Started rescan from block 000000000010934543170f0b95c7af69635510e1f6d763a22c0f155a2232493f (height 1569405) for 0 addresses
Jul 17 21:20:29 Crypthusiast lnd[3379]: 2019-07-17 21:20:29.465 [INF] LNWL: Catching up block hashes to height 1569406, this might take a while
Jul 17 21:20:29 Crypthusiast lnd[3379]: 2019-07-17 21:20:29.467 [INF] LNWL: Done catching up block hashes
Jul 17 21:20:29 Crypthusiast lnd[3379]: 2019-07-17 21:20:29.467 [INF] LNWL: Finished rescan for 0 addresses (synced to block 00000000000000ef0ef4af61cf7c5d2683c4713d01b32f16d98c811107583cc1, height 1569406)
Jul 17 21:20:32 Crypthusiast lnd[3379]: 2019-07-17 21:20:32.552 [ERR] SRVR: Unable to discover a UPnP enabled device on the local network: multiple NATs detected
Jul 17 21:20:32 Crypthusiast lnd[3379]: 2019-07-17 21:20:32.556 [INF] SRVR: Scanning local network for a NAT-PMP enabled device
Jul 17 21:20:32 Crypthusiast lnd[3379]: 2019-07-17 21:20:32.632 [ERR] SRVR: Unable to discover a NAT-PMP enabled device on the local network: unexpected result size 2, expected 12
Jul 17 21:20:32 Crypthusiast lnd[3379]: 2019-07-17 21:20:32.632 [ERR] SRVR: unable to create server: Unable to discover a NAT-PMP enabled device on the local network: unexpected result size 2, expected 12
Jul 17 21:20:32 Crypthusiast lnd[3379]: 2019-07-17 21:20:32.633 [INF] LTND: Shutdown complete
Jul 17 21:20:32 Crypthusiast lnd[3379]: Unable to discover a NAT-PMP enabled device on the local network: unexpected result size 2, expected 12

My Router is a Fritz!Box 6490 which seems working correctly. UPnP is allowed. Maybe somebody knows a solution. If any further information are needed. I'm happy to provide them to the best of my knowledge.
![1](https://user-images.githubusercontent.com/53018349/61405278-b33d0100-a8d9-11e9-85e2-06b71d82ac38.JPG)

**Comment by bruteforcecat** [comment]
I was also having the same problem. 

You can try `ufw disable` and restart your lnd to see if it's working. If that's the case, that's probably because your router is not using 1900 port for SSDP. you can set  `sudo ufw allow from 192.168.1.1` before finding out which port your router is using for upnp first.
