### ISSUE TITLE
Chris Belcher's pubkey has moved

### ISSUE THREAD

**Issue by thermalCat** [Stadicus/RaspiBolt#477]
attempting to get the file 
https://raw.githubusercontent.com/chris-belcher/electrum-personal-server/master/pgp/pubkeys/belcher.asc
as mentioned in the RaspiBolt bonus guide returns a 404:not found error.

as of 22 Apr 2019, Chris moved the pubkey to ...electrum-personal-server/docs/pubkeys/
with the comment "Remove pgp sigs as they are contained in releases".

**Comment by Septem151** [comment]
https://raw.githubusercontent.com/chris-belcher/electrum-personal-server/master/docs/pubkeys/belcher.asc is the current location of the PGP key. This has been updated already in commit [15be1a57bc6edac59c69d501483794ff4b71820e](https://github.com/Stadicus/RaspiBolt/commit/15be1a57bc6edac59c69d501483794ff4b71820e)

This issue may be closed.
