### ISSUE TITLE
Help! Stuck on Waiting for chain backend to finish sync 

### ISSUE THREAD

**Issue by KhimairaCrypto** [Stadicus/RaspiBolt#489]
I got this error [ERR] SRVR: Unable to discover a UPnP enabled device on the local network: context canceled,  So I decided to remove nat=true from lnd.conf

This is my lnd.conf fle
![lnd_conf](https://user-images.githubusercontent.com/36352470/65362282-1fc1dc80-dc4a-11e9-90d0-3539f56fbe5b.JPG)

I configured my ip as static on my router.

Ports 9735, 18333 are fully open according to https://www.yougetsignal.com/tools/open-ports/

I configured my router to forward 3 ports 
![PortFowarding](https://user-images.githubusercontent.com/36352470/65361993-1be18a80-dc49-11e9-98b3-384489fe60ee.jpg)

UFW is enabled and these are the rules:

![ufw_rules](https://user-images.githubusercontent.com/36352470/65362132-9e6a4a00-dc49-11e9-9f1c-5485ea318098.JPG)

These are some errors that I get when I execute tail -f /home/bitcoin/.bitcoin/testnet3/debug.log
![debug_log](https://user-images.githubusercontent.com/36352470/65363828-45061900-dc51-11e9-8bc4-160d6308017b.JPG)

I left the system run for several hours after unlocked the wallet and here are the loggs
![lnd_loggs](https://user-images.githubusercontent.com/36352470/65362390-9068f900-dc4a-11e9-8286-a615b4546aff.JPG)

As you can see the system seams stuck :-/. The other thing that I noticed, is that my wallet balance is zero.I followed the following instructions: https://stadicus.github.io/RaspiBolt/raspibolt_40_lnd.html#get-some-testnet-bitcoin

These is what I did to try to resolve my problem(s)
* Followed the troubleshooting section https://stadicus.github.io/RaspiBolt/raspibolt_70_troubleshooting.html
* Followed the recommendations from the following issues
https://github.com/Stadicus/RaspiBolt/issues/313
https://github.com/Stadicus/RaspiBolt/issues/396

Unfortunately I am stuck ;-/

**Comment by Septem151** [comment]
Looks like [that block](https://live.blockcypher.com/btc-testnet/block/00000000e603b46ede73d69c2aa9a4a08a5164d088534e8382de6e1536e600c2/) is indeed a valid block submitted roughly a year ago to the Bitcoin Testnet. I'm not sure why your node is marking the block as invalid... The only way I could see that being the case is if you had done the command `bitcoin-cli invalidateblock [block hash]`, or if you have a corrupt block.

https://bitcoin.stackexchange.com/questions/70083/block-338819-deemed-invalid-by-v0-15-1
may have the answer for you. In summary:

- Stop the LND service: `$ sudo systemctl stop lnd`
- Stop the bitcoin service: `$ sudo systemctl stop bitcoind`
- Switch to bitcoin user: `$ sudo su - bitcoin`
- Navigate to your blocks directory, delete the highest numbered `blk*.dat` and `rev*.dat` files (delete files with `rm [filename]`)
- Run the bitcoin daemon with the reindex command: `bitcoind -reindex -daemon`
- **Wait until reindex is complete, you may check the debug files at this time**
- Once you've caught up and synched with the testnet chain, stop bitcoind: `$ bitcoind stop`
- Start the bitcoind service again: `$ sudo systemctl start bitcoind`
- Verify you're all caught up, no errors, then start LND service: `$ sudo systemctl start lnd`
