### ISSUE TITLE
Trouble configuring Electrum to use my Pi

### ISSUE THREAD

**Issue by operahouserat** [Stadicus/RaspiBolt#494]
I've tried entering my pi's IP address into the server field under Electrum's network settings, as the guide suggests. However, after closing out, nothing happens in the console and the bottom left of the Electrum window reads "not connected". 

I've also tried entering the command line arguments directly into the console, but receive this syntax error: 

```
>> --oneserver --server 192.168.1.234:50002:s
Traceback (most recent call last):
                               ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "electrum/gui/qt/console.py", line 262, in runCommand
  File "<string>", line 1
    --oneserver --server 192.168.1.234:50002:s
                               ^
SyntaxError: invalid syntax
```

Any help would be appreciated.

**Comment by Stadicus** [comment]
I am using the Electum AppImage on Linux and the following command works:
```
./electrum-3.3.5-x86_64_6385067576d91c7b5b34ce44224adfa4.AppImage --oneserver --server 192.168.1.113:50002:s
```

If downloading the lastest version of Electrum does not solve that issue, I suggest opening an issue with them at https://github.com/spesmilo/electrum/.
