### ISSUE TITLE
UPnP error when starting LND

### ISSUE THREAD

**Issue by Stealth0113** [Stadicus/RaspiBolt#499]
I'm setting up an Bitcoin/LND node for the first time, the tutorial works very good. But when i'm starting LND i get an UPnP error. I saw several treats about this UPnP problem but non of them worked for me.

Here is the log when i started LND
![Log LND](https://user-images.githubusercontent.com/4562585/69492988-74334380-0ea9-11ea-9e19-ca5193d0bc88.png)

Port Forwarding:
![NAT](https://user-images.githubusercontent.com/4562585/69493051-45699d00-0eaa-11ea-8377-1b0d56332db8.png)
UPnP
![UPnP](https://user-images.githubusercontent.com/4562585/69493053-4b5f7e00-0eaa-11ea-86ac-bb0d0d62439a.png)
And the UFW settings:
![ufw](https://user-images.githubusercontent.com/4562585/69493058-57e3d680-0eaa-11ea-8e69-ddfe722982f2.png)

I really don't know what i'm doing wrong. I read the troubleshoot section and it works like a charm until i start LND.

Any suggestions where to look?

**Comment by Stealth0113** [comment]
I've Bitcoin Core 0.19 installed today on my windows laptop. Set port 8333 to my laptop instead of the raspberry pi and now my ip is visible on Bitnodes.  So the problem isn't in my router but in the PI settings.

**Comment by bruteforcecat** [comment]
I was also having the same problem but then it finds out my router is not using standard port 1900 for SSDP. you can check  if your firewall actually block those attempt from your router by `sudo dmesg | grep '\[UFW'`

You can try ufw disable and restart your lnd to see if it's working. If yes, you can set sudo ufw allow from 192.168.1.1(your router address) before finding out which port your router is using for upnp first.

**Comment by Stadicus** [comment]
For LND to be reachable from the outside, I'd recommend just using Tor, as UPnP may not work in every network and can be a pain to set up correctly.
