### ISSUE TITLE
JoinMarket on RaspiBolt

### ISSUE THREAD

**Issue by kristapsk** [Stadicus/RaspiBolt#503]
I am working on tutorial how to get JoinMarket working on RaspiBolt. Still consider it as work in progress, but is useful already, I think. https://github.com/kristapsk/raspibolt-extras/blob/master/joinmarket.md

Opening issue for two reasons: 1) for more RaspiBolt users to know about it, 2) should I send it in future PR as a part of RaspiBolt guide or just as a link in "Bonus Section > Even more Extras"?

**Comment by Stadicus** [comment]
Awesome! Currently swamped with other things, but I'll have a look as soon as I can.

**Comment by raindogdance** [comment]
FWIW, I followed that guide and can confirm that it worked for me just fine :) Thanks @kristapsk!  

Small suggestion: 

In [this](https://github.com/kristapsk/raspibolt-extras/blob/master/joinmarket.md#checking-wallet-balance-and-history) section I would also add `python wallet-tool.py wallet.jmdat display` command, because it allows the user to see the balances in different mixdepths at one glance.

**Comment by Stadicus** [comment]
For now, I'll try to keep the RaspiBolt guide to the essentials (Bitcoin, Electrum, Lightning) and have it accessible as a "Beginner's guide". So not planning to add JoinMarket, which is complex to setup and operate, as a main part. Happy to link to your guide from the bonus section, though.

Are you planning to keep it updated @kristapsk?

**Comment by kristapsk** [comment]
Yes, I'm planning to update the guide, currently waiting for next JoinMarket release which separates code and data (wallets, logs) directories, which makes setup and upgrade more easy (code on SD card, logs/wallets on HDD).

**Comment by Stadicus** [comment]
Cool! Will link it from the Bonus page, ok?

**Comment by kristapsk** [comment]
Probably I should finish it and then send a PR when I feel it's ready. Or you want to link WIP? Also, it's currently for RaspiBolt 1, need to check what's probably changed for RaspiBolt 2 (and probably need to order RPi 4 for myself, to test it).

**Comment by Stadicus** [comment]
Once you have everything ready and open the pull-request, I'll be happy to test it for the RaspiBolt2. There shouldn't be too many differences. One is that the external drive is now mounted to `/mnt/ext` instead of `/mnt/hdd`.
