### ISSUE TITLE
Last line of electrs.service file on Electrum instructions page needs correction if not installing Bitbox

### ISSUE THREAD

**Issue by nsclong** [Stadicus/RaspiBolt#516]
I believe the last line of the /etc/systemd/system/electrs.service file should be `WantedBy=multi-user.target` rather than 'WantedBy=bitboxbase.target'.
Otherwise systemd will not start Electrs correctly on reboot and Electrum wallets will be unable to connect after a reboot.

**Comment by Stadicus** [comment]
Thanks, that's a copy/paste error from my BitBoxBase project. Addressed in the pull request linked above.
