### ISSUE TITLE
Multi SSD RAID 0 Array

### ISSUE THREAD

**Issue by spookiestevie** [Stadicus/RaspiBolt#519]
I have a 500gb ssd, using a rough linear regression into the future of the past year of chain size growth, we will come close to this size in about 2 to 2.65 years. 

I think a guide on how to setup a raid 0 array on raspbian for the mount directory will be beneficial in the future allowing users to add multiple drives.

https://www.ricmedia.com/build-raspberry-pi3-raid-nas-server/

**Comment by Stadicus** [comment]
Thanks, good point. I think this is something for more advanced users, however. As a beginner's guide and with ever falling hardware prices, just swapping out the external drive every few years is probably the easier solution.

Will close as out-of-scope for now.
