### ISSUE TITLE
Is listenonion=1 necessary?

### ISSUE THREAD

**Issue by lobsterpub** [Stadicus/RaspiBolt#523]
From what I have read at: [https://github.com/bitcoin/bitcoin/blob/master/doc/tor.md#3-automatically-listen-on-tor](https://github.com/bitcoin/bitcoin/blob/master/doc/tor.md#3-automatically-listen-on-tor)

If you have listen=1 then listenonion is on by default if you are using Tor version 0.2.7.1 or higher.

From my own experience I only have listen=1 and I get incoming connections to my onion address.

**Comment by Stadicus** [comment]
Good point. I like specifying options explicitly, this is why I try usually even specify application defaults if they are important.
