### ISSUE TITLE
Symbolic link targeted appears in red.

### ISSUE THREAD

**Issue by miguelmartinn9** [Stadicus/RaspiBolt#539]
After running 
` ln -s /mnt/hdd/bitcoin /home/bitcoin/.bitcoin`
and checking with `ls -la`, it specifically says in the RP3 guide that _the target must not be red_ and mine is. 
Is this a problem? If it really is, how do I solve it?

**Comment by Stadicus** [comment]
That probably means that either
a) your external drive is not mounted correctly (check with `lsblk` to see if it shows a mountpoint), or
b) the `bitcoin` directory does not exist on the external drive (check with `ls -la /mnt/hdd/bitcoin`)

**Comment by Stadicus** [comment]
Any progress on that issue?

**Comment by miguelmartinn9** [comment]
Yes, yes. I already fixed it and my node is up and running. I am sorry for the delay in the response. The issue was the one you mentioned above: the bitcoin directory didn't exit. 
Thanks a lot!

**Comment by Stadicus** [comment]
Nice, thanks for confirming. Will close this issue.
