### ISSUE TITLE
Problem trying to link a directory to the external hard disk

### ISSUE THREAD

**Issue by miguelmartinn9** [Stadicus/RaspiBolt#542]
After running
ln -s /mnt/hdd/bitcoin /home/bitcoin/.bitcoin
and checking with ls -la, it specifically says in the RP3 guide that the target must not be red and mine is.
Is this a problem? If it really is, how do I solve it?

**Comment by Stadicus** [comment]
Closing as duplicate https://github.com/Stadicus/RaspiBolt/issues/539
