### ISSUE TITLE
Raspberrypi initial set up instructions

### ISSUE THREAD

**Issue by josh-kean** [Stadicus/RaspiBolt#549]
I had trouble creating the SSH file and the wpa_supplicant.conf file in the boot partition. Additionally, it wasn't explicit that the wpa_supplicant.conf file should also be saved in the boot partition.
My solution was creating both files with sudo permissions. Would you mind if I change the language or add a note with this information?

**Comment by Stadicus** [comment]
Thanks for the feedback, will do
