### ISSUE TITLE
BTC RPC Explorer - missing commentary?

### ISSUE THREAD

**Issue by waffi121** [Stadicus/RaspiBolt#569]
Many thanks for the instructions! 

I have just successfully installed the BTC RPC Explorer First I got connection errors. 
Only when I additionally commented out the line, everything worked. 

BTCEXP_BITCOIND_URI=bitcoin://raspibolt:****@127.0.0.1:8332?timeout=10000

Maybe add to it? Funny that it only works like that, I checked everything several times.

**Comment by Stadicus** [comment]
Thanks for your comment and I'm glad you got it working.

This setting should be commented out by default, however, so I don't think it should be mentioned explicitly. See here:

https://github.com/janoside/btc-rpc-explorer/blob/1bea8c26636b06c25f10b39d7ec1112ecd967ec0/.env-sample#L23
