### ISSUE TITLE
electrs connecting to bitcoind rpc port

### ISSUE THREAD

**Issue by compane** [Stadicus/RaspiBolt#579]
I guess I'm missing something. Why is there no rpc port in bitcoin.conf specified?

I'm getting this error in electrs startup:

`WARN - failed to connect daemon at 127.0.0.1:8332: Connection refused (os error 111)`

The error message is gone after adding "rpcport=8332" to bitcoin.conf.

**Comment by compane** [comment]
Adding "rpcport=8332" seems unrelated to the error. I removed the line and electrs is running without problems now. I'm clueless what the cause was.

**Comment by Stadicus** [comment]
Thanks for clarifying. RPC port is default `8332` and only needs to be specified if another value should be used.
