### ISSUE TITLE
User `electrs` not used for systemd unit

### ISSUE THREAD

**Issue by bjarnemagnussen** [Stadicus/RaspiBolt#588]
I am not completely sure if this is a mistake or not, but Raspibolt creates a dedicated user `electrs`, but does not make use of it inside the systemd unit in `/etc/systemd/system/electrs.service`:

```
# Directory creation and permissions
####################################

User=bitcoin
Group=bitcoin
```

I had to change the User to `electrs`, as there were otherwise problems with the locking of the electrs database.

**Comment by Stadicus** [comment]
Nice find, thanks for reporting! That change was actually not supposed to be commited to master already, it was an unitended relict from an experiment. 

I'm looking for a simple way to run Electrs with a separate user, but `bitcoind` is tricky with file-based permissions, creating new files always with (`600`)... Probably need to use the `sysperms` option.

Reverted this change in https://github.com/Stadicus/RaspiBolt/commit/dec615a90e0b7bfe25ef5188ae59df364b9cca7c, so running Electrs as user "bitcoin" is currently correct.

Sorry for the confusion, you can delete the user "electrs" for now and set the file permissions to "bitcoin:bitcoin".
