### ISSUE TITLE
Why do I have to update and why am I unreachable?  

### ISSUE THREAD

**Issue by miguelmartinn9** [Stadicus/RaspiBolt#595]
So a few months ago I unplugged my bitcoin node when it was running perfectly. So when I connected it again this week I had to let it sync to the blockchain again. Now you can see it's synced but I have several issues. 
It tells me to update the version when v0.19.0.1 is totally up to date. And if I need to update, how do I do it? 
Secondly I don't know but it says that my node is unreachable (I cropped out the IP address). How can I fix it? 

Thanks
![Screenshot from 2020-04-24 21-14-15](https://user-images.githubusercontent.com/39597568/80248629-9d324d00-8670-11ea-820e-b44b6bdaffcc.png)

**Comment by Xekyo** [comment]
The latest release of Bitcoin Core is [`v0.19.1`](https://bitcoin.org/en/release/v0.19.1) which is newer than the `v0.19.0.1` you're running. The [RaspiBolt FAQ](https://stadicus.github.io/RaspiBolt/raspibolt_faq.html#how-to-upgrade-bitcoin-core) gives instructions on how to update.

I don't know about the "Not reachable".

**Comment by miguelmartinn9** [comment]
Thanks about the update. The unreachable thing it's because I am having problems with my ISP and port forwarding. Thanks!

**Comment by 53645714n** [comment]
Did you try the bitnodes way? I added it to the motd file, just have to fiddle with comment tags, it's in the tutorial.

25 apr. 2020 23:57:20 miguelmartinn9 <notifications@github.com>:

**Comment by miguelmartinn9** [comment]
Nope, I haven't what is there to try?

**Comment by 53645714n** [comment]
There's multiple ways of checking if your node is reachable, one is via pinging your own address which is failing, the second is via bitnodes.earn. Both ways are programmed in the motd, one of them is commented out.
If you have incoming connections however, you don't need to worry. That is the best indicator.

26 apr. 2020 00:09:02 miguelmartinn9 <notifications@github.com>:

**Comment by miguelmartinn9** [comment]
I have one last question. If I don't have any incoming connections (which I don't, I only have outgoing) can I connect my node to Electrum like it says [here](https://stadicus.github.io/RaspiBolt/raspibolt_50_electrs.html#connect-electrum-wallet)?
