### ISSUE TITLE
Bitcoind and lnd updated but

### ISSUE THREAD

**Issue by ivoryz** [Stadicus/RaspiBolt#596]
Hi, I just updated bitcoind and lnd to their last versions.
I restarted my raspibolt, I unlocked the wallet, all the services are running, but now I receive this error

[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

I think I'm missing some steps

**Comment by 53645714n** [comment]
Good to hear. How fast are you? I have this error sometimes if not everything is up and running, can take a while.

25 apr. 2020 18:12:19 Ivory <notifications@github.com>:

**Comment by ivoryz** [comment]
Everything it's ok now! thank you
