### ISSUE TITLE
what does it mean when two of my peers are from 127.0.0.1?

### ISSUE THREAD

**Issue by 3ntranced** [Stadicus/RaspiBolt#600]
``

11 | /Satoshi:0.19.1/ | 127.0.0.1:57856 | 0000000000000409 | 0:02 / 0:02
-- | -- | -- | -- | --
12 | /Satoshi:0.19.0.1/ | 127.0.0.1:39460 | 0000000000000409 | 0:02 / 0:03

**Comment by 3ntranced** [comment]
and in debug.log I am getting the following entries
2020-05-03T05:19:16Z ThreadRPCServer incorrect password attempt from 127.0.0.1:37494
2020-05-03T05:20:20Z ThreadRPCServer incorrect password attempt from 127.0.0.1:37558

**Comment by Stadicus** [comment]
Are you running the BTC RPC Explorer, or Electrs or additional software?

**Comment by 3ntranced** [comment]
Yes BTC RPC explorer and Electrs. Is it them?

**Comment by Stadicus** [comment]
Probably. You should be able to see unsuccessful connection attempts in the logfiles of either of these two services. Or you just stop one, and see if the errors in the bitcoind log stop.
