### ISSUE TITLE
Raspi-Config: Wrong options described on guide

### ISSUE THREAD

**Issue by dellagustin** [Stadicus/RaspiBolt#675]
Hello, I am following the guide now for the first time.

One the Raspi-Config section I noticed that the order of the options is different:
Password is on 1 -> S3
Hostname is on 1 -> S4
Wifi 1 -> S1
Boot Options - Console 1 -> S5
Wait for network at boot -> 1 -> S6
Expand filesystem 6 ->A1

![image](https://user-images.githubusercontent.com/260113/102273270-5a382900-3f22-11eb-820b-7b02bc36de24.png)

**Comment by Stadicus** [comment]
Thanks. I need to update screenshots (and maybe even videos) to the latest Raspbian version.
