### ISSUE TITLE
The LND Auto Unlock Script requires jq

### ISSUE THREAD

**Issue by schulzemic** [Stadicus/RaspiBolt#761]
jq doesn't seem to be installed on Raspberry Pi OS by default. Maybe you want to add `sudo apt install jq` to the instructions.

**Comment by vicariousdrama** [comment]
It's not there in Raspberry Pi OS by default, but it is part of the instructions already.

See
https://github.com/Stadicus/RaspiBolt/blob/master/raspibolt_20_pi.md#software-update

**Comment by schulzemic** [comment]
Ah, you're right. I had looked for it, but in the "Bonus Section". Sorry.
